version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: inkdb
      POSTGRES_USER: inkadmin
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
