version: '3.8'
services:
  redis:
    image: redis

  db:
    image: postgres
    environment:
      POSTGRES_DB: inkdb
      POSTGRES_USER: inkadmin
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ink@inception.com
      PGADMIN_DEFAULT_PASSWORD: inkadmin
    depends_on:
      - db

  minio:
    image: minio/minio:latest
    volumes:
      - ./minio_data:/minio_files
    environment:
      MINIO_ROOT_USER: minioaccess
      MINIO_ROOT_PASSWORD: miniopass
    command: 'minio server /minio_files --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db
      - redis
    expose:
      - "8000"

  nginx:
    build: ./devops/nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - web

volumes:
  postgres_data:
  minio_data:
  static_volume:
  media_volume:
