"""
Django settings for ink_inception project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from celery.schedules import crontab
from corsheaders.defaults import default_headers as cors_default_headers
from django.utils.timezone import timedelta

from config.celery.queue import CeleryQueue

from . import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PRODUCTION = os.getenv("PRODUCTION") == "True"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", "*****")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", True)
PRODUCTION = env.bool("PRODUCTION", False)

ALLOWED_HOSTS = env.list("ALLOWED_HOST", default=["*"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_celery_beat",
    "drf_yasg",
    "storages",
]

PROJECT_APPS = [
    "core.v1.users.apps.UsersConfig",
    "core.v1.blogs.apps.BlogsConfig",
    "core.v1.authentication.apps.AuthenticationConfig",
]

INSTALLED_APPS += PROJECT_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.utils.middlewares.LoggingMiddleware",
    "core.utils.middlewares.ExceptionMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("DJANGO_POSTGRES_NAME", "testdb"),
        "USER": env.str("DJANGO_POSTGRES_USER", "testuser"),
        "PASSWORD": env.str("DJANGO_POSTGRES_PASSWORD", "password"),
        "HOST": env.str("DJANGO_POSTGRES_HOST", "localhost"),
        "PORT": env.str("DJANGO_POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

#   CORS
if not env.bool("DJANGO_CORS_ALLOW_ALL_ORIGINS", default=False):
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = env.list(
        "DJANGO_CORS_ALLOWED_ORIGINS",
        default=[],
    )
else:
    CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = list(cors_default_headers) + [
    "secret-key",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_THROTTLE_CLASSES": ["rest_framework.throttling.AnonRateThrottle"],
    "DEFAULT_THROTTLE_RATES": {"anon": "50/minute"},
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=120),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "UPDATE_LAST_LOGIN": True,
}

#   User Model
AUTH_USER_MODEL = "users.User"

# Auth Backend
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# Session Engine
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

# ___________ API AND VERSIONING ____________
API_VERSION = env.str("API_VERSION", default="1")


EMAIL_VERIFICATION_TOKEN_EXPIRATION_SECS = env.int(
    "DJANGO_EMAIL_VERIFICATION_TOKEN_EXPIRATION_SECS", default=(60 * 10)
)

EMAIL_LOGIN_TOKEN_EXPIRATION_SECS = env.int(
    "DJANGO_EMAIL_LOGIN_TOKEN_EXPIRATION_SECS", default=(60 * 10)
)

DJANGO_EMAIL_LOGIN_MASTER_TOKEN = env.str(
    "DJANGO_EMAIL_LOGIN_MASTER_TOKEN", default=SECRET_KEY
)

# ______________________REDIS____________________________
REDIS_HOST = env.str("REDIS_HOST", default="localhost")
REDIS_PORT = env.int("REDIS_PORT", default=6379)

# ______________________ Cache _______________________________
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}",
    }
}

CACHE_TTL = env.int("VIEW_CACHE_TTL_SECS", 60 * 15)


# ___________________________________Celery_________________________________________
CELERY_BROKER = env.str("CELERY_BROKER")
CELERY_BROKER_URL = CELERY_BROKER
CELERY_RESULT_BACKEND = env.str("CELERY_BACKEND")
CELERY_TIMEZONE = env.str("CELERY_TIMEZONE", default="UTC")
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERYD_PREFETCH_MULTIPLIER = 1
CELERY_QUEUES = CeleryQueue.queues()


CELERY_BEAT_SCHEDULE = {
    "clear_out_expired_periodic_tasks": {
        "task": "core.utils.tasks.clear_out_periodic_tasks",
        "schedule": crontab(hour="*/2"),
        "options": {"queue": "beats"},
    },
    "price_trigger_checker": {
        "task": "core.utils.tasks.price_fetcher",
        "schedule": timedelta(seconds=8),
        "options": {"queue": "beats"},
    },
}


# ___________EMAIL______________________
EMAIL_BACKEND = env.str("EMAIL_BACKEND", default="***")
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", True)
EMAIL_USE_TSL = env.bool("EMAIL_USE_TSL", False)
EMAIL_HOST = env.str("EMAIL_HOST", default="***")
EMAIL_PORT = env.int("EMAIL_PORT", 465)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="***")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="***")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"}
    }
}


# ___________S3______________________
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# Base settings for S3


if os.getenv("PRODUCTION") == "False":
    AWS_ACCESS_KEY_ID = os.getenv("MINIO_ACCESS_KEY_ID", "minioaccesskey")
    AWS_SECRET_ACCESS_KEY = os.getenv("MINIO_SECRET_ACCESS_KEY", "miniosecretkey")
    AWS_STORAGE_BUCKET_NAME = os.getenv("MINIO_STORAGE_BUCKET_NAME", "my-local-bucket")
    AWS_S3_ENDPOINT_URL = os.getenv("MINIO_ENDPOINT_URL", "http://minio:9000")
    AWS_S3_CUSTOM_DOMAIN = None
    AWS_S3_USE_SSL = os.getenv("MINIO_USE_SSL", False)
else:
    AWS_ACCESS_KEY_ID = os.getenv("AWS_S3_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_S3_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_S3_STORAGE_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
    AWS_S3_USE_SSL = os.getenv("AWS_S3_USE_SSL") == "True"

# Configuring storage backends
STATIC_URL = "/static/"
STATICFILES_LOCATION = "static"
STATICFILES_STORAGE = "core.utils.helpers.storage.S3StaticStorage"

MEDIA_URL = "/media/"
DEFAULT_FILE_STORAGE = "core.utils.helpers.storage.S3MediaStorage"
