name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies locally
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Ensure remote directory exists
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} "mkdir -p /home/ubuntu/ink-inception-backend"

      - name: Copy files to EC2
        run: |
          scp -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no -r ./* ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/ink-inception-backend

      - name: SSH into EC2 and run deployment scripts
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /home/ubuntu/ink-inception-backend
          # Ensure virtual environment is activated
          if [ ! -d "env" ]; then
            python3 -m venv env
          fi
          source env/bin/activate
          pip install -r requirements.txt
          # Restart the application using PM2
          pm2 restart ink-inception-backend || pm2 start gunicorn --name ink-inception-backend --interpreter python3 -- gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
          EOF
